In [96]:
import pandas as pd
import numpy as np
import sklearn as skl
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
from tensorflow import keras
from sklearn.metrics import r2_score
import statsmodels.api as sm

In [97]:
player_data = pd.read_csv('/Users/hunter/Desktop/Data_Class/final_project/Data/cleaned_players.csv')

In [98]:
player_data

Player Pos   Min  Gls  Ast   xG  npxG   xA  Sh  SoT  ...  Fld  \
0      Roberto Firmino  FW  86.0    0    1  0.9   0.9  0.4   4    1  ...    1   
1         James Milner  CM   4.0    0    0  0.0   0.0  0.0   0    0  ...    0   
2         Divock Origi  LW  74.0    1    0  0.2   0.2  0.0   1    1  ...    2   
3           Sadio Mané  LW  16.0    0    0  0.0   0.0  0.0   0    0  ...    0   
4        Mohamed Salah  RW  90.0    1    1  0.3   0.3  0.2   2    1  ...    1   
...                ...  ..   ...  ...  ...  ...   ...  ...  ..  ...  ...  ...   
20370     Riyad Mahrez  CM  90.0    1    2  0.1   0.1  0.5   2    2  ...    1   
20371  Christian Fuchs  LB  90.0    0    0  0.0   0.0  0.0   0    0  ...    0   
20372    Harry Maguire  CB  90.0    0    0  0.4   0.4  0.0   4    1  ...    1   
20373       Wes Morgan  CB  90.0    0    0  0.0   0.0  0.0   0    0  ...    0   
20374  Hamza Choudhury  RB  34.0    0    0  0.0   0.0  0.0   1    0  ...    1   

       Crs  TklW  Int  CrdY  CrdR  year  fantasy_points  Position Group League  
0        0     1    0     0     0  2019            10.0         Forward     PL  
1        0     0    0     0     0  2019             1.0        Midfield     PL  
2        4     3    1     0     0  2019            15.0         Forward     PL  
3        0     0    0     0     0  2019             1.0         Forward     PL  
4        7     0    0     0     0  2019            17.5         Forward     PL  
...    ...   ...  ...   ...   ...   ...             ...             ...    ...  
20370    4     1    1     0     0  2018            25.0        Midfield     PL  
20371    1     0    4     0     0  2018             2.0        Defender     PL  
20372    0     2    5     0     0  2018             8.0        Defender     PL  
20373    0     0    3     0     0  2018             2.5        Defender     PL  
20374    0     0    4     1     0  2018            -0.5        Defender     PL  

[20375 rows x 21 columns]

In [99]:
forward_data = player_data[player_data['Position Group'] == 'Forward']
forward_data

Player Pos   Min  Gls  Ast   xG  npxG   xA  Sh  SoT  ...  Fld  \
0      Roberto Firmino  FW  86.0    0    1  0.9   0.9  0.4   4    1  ...    1   
2         Divock Origi  LW  74.0    1    0  0.2   0.2  0.0   1    1  ...    2   
3           Sadio Mané  LW  16.0    0    0  0.0   0.0  0.0   0    0  ...    0   
4        Mohamed Salah  RW  90.0    1    1  0.3   0.3  0.2   2    1  ...    1   
12         Teemu Pukki  FW  83.0    1    0  0.4   0.4  0.1   3    1  ...    1   
...                ...  ..   ...  ...  ...  ...   ...  ...  ..  ...  ...  ...   
20353       Harry Kane  FW  90.0    2    0  0.2   0.2  0.0   3    2  ...    0   
20354      Lucas Moura  LW  74.0    0    1  0.1   0.1  0.0   2    0  ...    2   
20356      Érik Lamela  RW  78.0    2    0  1.3   1.3  0.0   2    2  ...    2   
20361    Son Heung-min  FW   6.0    0    0  0.0   0.0  0.0   0    0  ...    0   
20366      Jamie Vardy  FW  90.0    2    0  0.5   0.5  0.3   6    2  ...    0   

       Crs  TklW  Int  CrdY  CrdR  year  fantasy_points  Position Group League  
0        0     1    0     0     0  2019            10.0         Forward     PL  
2        4     3    1     0     0  2019            15.0         Forward     PL  
3        0     0    0     0     0  2019             1.0         Forward     PL  
4        7     0    0     0     0  2019            17.5         Forward     PL  
12       0     1    1     0     0  2019            15.0         Forward     PL  
...    ...   ...  ...   ...   ...   ...             ...             ...    ...  
20353    0     0    0     0     0  2018            24.5         Forward     PL  
20354    0     0    0     0     0  2018             5.0         Forward     PL  
20356    1     1    2     0     0  2018            26.5         Forward     PL  
20361    0     0    0     0     0  2018             1.0         Forward     PL  
20366    0     0    0     0     0  2018            25.0         Forward     PL  

[5463 rows x 21 columns]

In [100]:
# Groupby player (forward) mean
forward_data_mean = forward_data.groupby(["Player"]).mean()
forward_data_mean.head()

Min       Gls       Ast        xG      npxG        xA  \
Player                                                                        
Aaron Connolly  49.312500  0.125000  0.000000  0.137500  0.137500  0.012500   
Aaron Lennon    73.611111  0.055556  0.055556  0.016667  0.016667  0.050000   
Aaron Mooy      73.846154  0.000000  0.000000  0.053846  0.053846  0.207692   
Adam Idah       65.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
Adam Lallana    23.076923  0.000000  0.076923  0.046154  0.046154  0.023077   

                      Sh       SoT       Fls       Fld       Crs      TklW  \
Player                                                                       
Aaron Connolly  1.437500  0.500000  0.687500  1.625000  0.437500  0.250000   
Aaron Lennon    0.388889  0.166667  0.722222  1.055556  1.777778  0.888889   
Aaron Mooy      1.384615  0.615385  0.384615  0.615385  5.923077  1.461538   
Adam Idah       0.000000  0.000000  0.000000  2.000000  0.000000  3.000000   
Adam Lallana    0.461538  0.000000  0.307692  0.692308  0.538462  0.230769   

                     Int      CrdY  CrdR         year  fantasy_points  
Player                                                                 
Aaron Connolly  0.000000  0.000000   0.0  2019.187500        3.156250  
Aaron Lennon    0.500000  0.055556   0.0  2017.611111        2.138889  
Aaron Mooy      0.384615  0.153846   0.0  2018.846154        2.846154  
Adam Idah       0.000000  0.000000   0.0  2020.000000        2.500000  
Adam Lallana    0.230769  0.153846   0.0  2018.307692        1.230769

In [101]:
forward_players = forward_data_mean.filter(['Player'], axis=1)
forward_players

Empty DataFrame
Columns: []
Index: [Aaron Connolly, Aaron Lennon, Aaron Mooy, Adam Idah, Adam Lallana, Adam Smith, Adama Traoré, Ahmed Elmohamady, Ainsley Maitland-Niles, Albian Ajeti, Alex Iwobi, Alex Oxlade-Chamberlain, Alexandre Lacazette, Alexis Mac Allister, Alireza Jahanbakhsh, Allan Saint-Maximin, Andre Gray, Andreas Pereira, Andriy Yarmolenko, Andros Townsend, Andy Carroll, Angel Gomes, Anthony Gordon, Anthony Martial, Anwar El Ghazi, Armando Broja, Arthur Masuaku, Ashley Barnes, Ayoze Pérez, Ben Chilwell, Ben Osborn, Bernard, Bernardo, Bernardo Silva, Billy Sharp, Borja Bastón, Brandon Williams, Bukayo Saka, Callum Hudson-Odoi, Callum Robinson, Callum Wilson, Calum Chambers, Carlos Sánchez, Cenk Tosun, Che Adams, Cheikhou Kouyaté, Chris Wood, Christian Atsu, Christian Benteke, Christian Eriksen, Christian Pulisic, Ciaran Clark, Connor Wickham, Conor Hourihane, Dan Gosling, Daniel James, Daniel Podence, Danny Ings, Danny Rose, Danny Welbeck, David McGoldrick, DeAndre Yedlin, Declan Rice, Dejan Lovren, Dele Alli, Demarai Gray, Dennis Srbeny, Diego Rico, Diogo Dalot, Diogo Jota, Divock Origi, Domingos Quina, Dominic Calvert-Lewin, Dominic Solanke, Douglas Luiz, Dwight Gayle, Dwight McNeil, Eddie Nketiah, Ederson, Emerson Palmieri, Emi Buendía, Emil Krafth, Eric Dier, Ezequiel Schelotto, Fabinho, Faustino Anjorin, Felipe Anderson, Florin Andone, Gabriel Jesus, Georges-Kévin N'Koudou, Gerard Deulofeu, Giovani Lo Celso, Glenn Murray, Gylfi Sigurðsson, Hamza Choudhury, Harry Kane, Harry Wilson, Harry Winks, Harvey Barnes, Henri Lansbury, ...]

[251 rows x 0 columns]

In [102]:
#def label_assists (row):
#    if row['Ast'] >  0:
#        return True
#    return False
#forward_data_mean["Assist_Y/N"] = forward_data_mean.apply(lambda row: label_assists(row), axis=1)

In [103]:
#forward_data_mean

In [104]:
forward_data_mean.shape

(251, 17)

In [105]:
def backwardElimination(x, sl):
    numVars = len(x[0])
    for i in range(0, numVars):
        regressor_OLS = sm.OLS(y_var, x).fit()
        maxVar = max(regressor_OLS.pvalues).astype(float)
        if maxVar > sl:
            for j in range(0, numVars - i):
                if (regressor_OLS.pvalues[j].astype(float) == maxVar):
                    x = np.delete(x, j, 1)
    regressor_OLS.summary()
    return x

In [106]:
# Create target
y_var = forward_data_mean.Ast
y_var.head()

Player
Aaron Connolly    0.000000
Aaron Lennon      0.055556
Aaron Mooy        0.000000
Adam Idah         0.000000
Adam Lallana      0.076923
Name: Ast, dtype: float64

In [107]:
player_x = forward_data_mean.drop("Ast", axis =1)
player_x.head()

Min       Gls        xG      npxG        xA        Sh  \
Player                                                                        
Aaron Connolly  49.312500  0.125000  0.137500  0.137500  0.012500  1.437500   
Aaron Lennon    73.611111  0.055556  0.016667  0.016667  0.050000  0.388889   
Aaron Mooy      73.846154  0.000000  0.053846  0.053846  0.207692  1.384615   
Adam Idah       65.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
Adam Lallana    23.076923  0.000000  0.046154  0.046154  0.023077  0.461538   

                     SoT       Fls       Fld       Crs      TklW       Int  \
Player                                                                       
Aaron Connolly  0.500000  0.687500  1.625000  0.437500  0.250000  0.000000   
Aaron Lennon    0.166667  0.722222  1.055556  1.777778  0.888889  0.500000   
Aaron Mooy      0.615385  0.384615  0.615385  5.923077  1.461538  0.384615   
Adam Idah       0.000000  0.000000  2.000000  0.000000  3.000000  0.000000   
Adam Lallana    0.000000  0.307692  0.692308  0.538462  0.230769  0.230769   

                    CrdY  CrdR         year  fantasy_points  
Player                                                       
Aaron Connolly  0.000000   0.0  2019.187500        3.156250  
Aaron Lennon    0.055556   0.0  2017.611111        2.138889  
Aaron Mooy      0.153846   0.0  2018.846154        2.846154  
Adam Idah       0.000000   0.0  2020.000000        2.500000  
Adam Lallana    0.153846   0.0  2018.307692        1.230769

In [108]:
player_x.shape

(251, 16)

In [109]:
# Create features 
X = player_x
X.head()

Min       Gls        xG      npxG        xA        Sh  \
Player                                                                        
Aaron Connolly  49.312500  0.125000  0.137500  0.137500  0.012500  1.437500   
Aaron Lennon    73.611111  0.055556  0.016667  0.016667  0.050000  0.388889   
Aaron Mooy      73.846154  0.000000  0.053846  0.053846  0.207692  1.384615   
Adam Idah       65.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
Adam Lallana    23.076923  0.000000  0.046154  0.046154  0.023077  0.461538   

                     SoT       Fls       Fld       Crs      TklW       Int  \
Player                                                                       
Aaron Connolly  0.500000  0.687500  1.625000  0.437500  0.250000  0.000000   
Aaron Lennon    0.166667  0.722222  1.055556  1.777778  0.888889  0.500000   
Aaron Mooy      0.615385  0.384615  0.615385  5.923077  1.461538  0.384615   
Adam Idah       0.000000  0.000000  2.000000  0.000000  3.000000  0.000000   
Adam Lallana    0.000000  0.307692  0.692308  0.538462  0.230769  0.230769   

                    CrdY  CrdR         year  fantasy_points  
Player                                                       
Aaron Connolly  0.000000   0.0  2019.187500        3.156250  
Aaron Lennon    0.055556   0.0  2017.611111        2.138889  
Aaron Mooy      0.153846   0.0  2018.846154        2.846154  
Adam Idah       0.000000   0.0  2020.000000        2.500000  
Adam Lallana    0.153846   0.0  2018.307692        1.230769

In [110]:
X_opt = X.iloc[:,:].values
X_opt

array([[4.93125000e+01, 1.25000000e-01, 1.37500000e-01, ...,
        0.00000000e+00, 2.01918750e+03, 3.15625000e+00],
       [7.36111111e+01, 5.55555556e-02, 1.66666667e-02, ...,
        0.00000000e+00, 2.01761111e+03, 2.13888889e+00],
       [7.38461538e+01, 0.00000000e+00, 5.38461538e-02, ...,
        0.00000000e+00, 2.01884615e+03, 2.84615385e+00],
       ...,
       [4.26969697e+01, 6.06060606e-02, 1.51515152e-01, ...,
        0.00000000e+00, 2.01833333e+03, 2.06060606e+00],
       [9.00000000e+00, 0.00000000e+00, 2.00000000e-01, ...,
        0.00000000e+00, 2.01700000e+03, 2.00000000e+00],
       [6.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 1.00000000e+00]])

In [111]:
y_var = y_var.reset_index().iloc[:,1:].values

In [112]:
# Test if features are siginiicant 
trimmed_X = backwardElimination(X_opt, 0.05)
trimmed_X

array([[1.25000000e-01, 1.43750000e+00, 5.00000000e-01, ...,
        0.00000000e+00, 2.01918750e+03, 3.15625000e+00],
       [5.55555556e-02, 3.88888889e-01, 1.66666667e-01, ...,
        0.00000000e+00, 2.01761111e+03, 2.13888889e+00],
       [0.00000000e+00, 1.38461538e+00, 6.15384615e-01, ...,
        0.00000000e+00, 2.01884615e+03, 2.84615385e+00],
       ...,
       [6.06060606e-02, 1.09090909e+00, 3.03030303e-01, ...,
        0.00000000e+00, 2.01833333e+03, 2.06060606e+00],
       [0.00000000e+00, 2.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 2.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 1.00000000e+00]])

In [113]:
# Split our preprocessed data into our features and target arrays
y = y_var
X = trimmed_X

In [114]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [115]:
# Create scaler instance
scaler = StandardScaler()

In [116]:
# Fit the scaler
X_scaler = scaler.fit(X_train)

In [117]:
# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [118]:
# Define the linear regression model
lin_reg = LinearRegression()

In [119]:
# Train the model
lin_reg.fit(X_train_scaled, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [120]:
lin_reg.score(X_train, y_train)

-375.1997653160606

In [121]:
lin_reg.score(X_test, y_test)

-330.16219136233076

In [122]:
y_pred = lin_reg.predict(X_test)

In [123]:
y_pred_all = lin_reg.predict(X)

In [124]:
y_pred_all.shape

(251, 1)

In [125]:
#y_pred_nn = nn.predict(X)

In [126]:
#y_var["Ast"].count()
#unique, counts = np.unique(y, return_counts = True)
#dict(zip(unique, counts))

In [127]:
#y_pred_nn.shape

In [128]:
#y_pred_nn

In [129]:
r2_score(y_test, y_pred)

-330.16219136233076

In [130]:
# Define hidden layers
number_input_features = len(X_train_scaled[0])
hidden_layer1 = 50
hidden_layer2 = 50

In [131]:
nn = tf.keras.models.Sequential()

In [132]:
# Hidden layer 1
nn.add(tf.keras.layers.Dense(units=hidden_layer1, input_dim=number_input_features, kernel_initializer='normal', activation="relu"))

In [133]:
# Hidden layer 2
nn.add(tf.keras.layers.Dense(units=hidden_layer2, input_dim=number_input_features, kernel_initializer='normal',  activation="relu"))

In [134]:
# Output layer
nn.add(tf.keras.layers.Dense(units=1))

In [135]:
# Compile the model
#nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
nn.compile(loss="mean_squared_error", optimizer="adam")#, metrics=["accuracy"])

In [136]:
# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 50)                600       
_________________________________________________________________
dense_7 (Dense)              (None, 50)                2550      
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 51        
Total params: 3,201
Trainable params: 3,201
Non-trainable params: 0
_________________________________________________________________


In [137]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Train on 188 samples
Epoch 1/100
188/188 [==============================] - 1s 4ms/sample - loss: 0.0124
Epoch 2/100
188/188 [==============================] - 0s 187us/sample - loss: 0.0075
Epoch 3/100
188/188 [==============================] - 0s 194us/sample - loss: 0.0059
Epoch 4/100
188/188 [==============================] - 0s 156us/sample - loss: 0.0049
Epoch 5/100
188/188 [==============================] - 0s 137us/sample - loss: 0.0044
Epoch 6/100
188/188 [==============================] - 0s 133us/sample - loss: 0.0042
Epoch 7/100
188/188 [==============================] - 0s 130us/sample - loss: 0.0038
Epoch 8/100
188/188 [==============================] - 0s 122us/sample - loss: 0.0035
Epoch 9/100
188/188 [==============================] - 0s 125us/sample - loss: 0.0033
Epoch 10/100
188/188 [==============================] - 0s 155us/sample - loss: 0.0031
Epoch 11/100
188/188 [==============================] - 0s 118us/sample - loss: 0.0029
Epoch 12/100
188/188 [===========

188/188 [==============================] - 0s 128us/sample - loss: 8.1016e-06
Epoch 92/100
188/188 [==============================] - 0s 112us/sample - loss: 7.7591e-06
Epoch 93/100
188/188 [==============================] - 0s 121us/sample - loss: 8.2887e-06
Epoch 94/100
188/188 [==============================] - 0s 101us/sample - loss: 8.6303e-06
Epoch 95/100
188/188 [==============================] - 0s 104us/sample - loss: 6.4951e-06
Epoch 96/100
188/188 [==============================] - 0s 99us/sample - loss: 8.2965e-06
Epoch 97/100
188/188 [==============================] - 0s 120us/sample - loss: 1.0186e-05
Epoch 98/100
188/188 [==============================] - 0s 101us/sample - loss: 9.7734e-06
Epoch 99/100
188/188 [==============================] - 0s 99us/sample - loss: 1.0503e-05
Epoch 100/100
188/188 [==============================] - 0s 102us/sample - loss: 7.7740e-06


In [138]:
# Evaluate the model using the test data - mean
# model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)
model_loss = nn.evaluate(X_test_scaled, y_test, verbose=2)
#print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

print(f"Loss: {model_loss}")

63/1 - 0s - loss: 0.0013
Loss: 0.0011352280114171288


In [139]:
#y_pred.shape
y_pred_all.shape

(251, 1)

In [140]:
#y_pred
y_pred_all

array([[ 1.58645372],
       [ 1.14320335],
       [ 1.35685046],
       [ 1.24938848],
       [ 0.6986472 ],
       [ 0.60103858],
       [ 1.73337247],
       [ 0.26842622],
       [ 6.43101322],
       [ 0.29718099],
       [ 2.09294594],
       [ 1.64747579],
       [ 3.56159818],
       [ 0.78441492],
       [ 1.39301991],
       [ 2.13629195],
       [ 2.08092717],
       [ 0.73766536],
       [ 0.94313232],
       [ 2.09826999],
       [ 0.89685339],
       [ 1.47713914],
       [ 1.05516439],
       [ 3.52568232],
       [ 2.35657084],
       [ 0.60103858],
       [ 2.00579795],
       [ 2.25637195],
       [ 3.22093259],
       [ 0.16036791],
       [ 1.03327185],
       [ 1.46075263],
       [ 1.92031868],
       [ 2.84938215],
       [ 1.1980738 ],
       [ 0.60103858],
       [ 0.60103858],
       [ 0.78212832],
       [ 1.49515995],
       [ 1.08470278],
       [ 2.90141545],
       [ 0.16036791],
       [ 0.60103858],
       [ 2.04877353],
       [ 0.84509098],
       [ 0

In [141]:
#np.rint(y_pred)
y_pred_all_clean = np.rint(y_pred_all)
y_pred_all_clean

array([[ 2.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 2.],
       [ 0.],
       [ 6.],
       [ 0.],
       [ 2.],
       [ 2.],
       [ 4.],
       [ 1.],
       [ 1.],
       [ 2.],
       [ 2.],
       [ 1.],
       [ 1.],
       [ 2.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 4.],
       [ 2.],
       [ 1.],
       [ 2.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 3.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 1.],
       [ 1.],
       [ 3.],
       [ 1.],
       [ 1.],
       [ 4.],
       [ 4.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 2.],
       [ 1.],
       [ 4.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 3.],
       [ 2.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 3.],
       [ 2.],
      

In [142]:
y_pred_all_clean[y_pred_all_clean <= 0] = 0
y_pred_all_clean

array([[2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [0.],
       [6.],
       [0.],
       [2.],
       [2.],
       [4.],
       [1.],
       [1.],
       [2.],
       [2.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [4.],
       [2.],
       [1.],
       [2.],
       [2.],
       [3.],
       [0.],
       [1.],
       [1.],
       [2.],
       [3.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [3.],
       [0.],
       [1.],
       [2.],
       [1.],
       [1.],
       [3.],
       [1.],
       [1.],
       [4.],
       [4.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [4.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [3.],
       [2.],
       [0.],
       [1.],
       [1.],
       [3.],
       [2.],
       [0.],
       [2.],
       [1.],
       [1.],
       [2.],
       [3.],

In [143]:
forward_players['Pred_Ast'] = y_pred_all_clean
forward_players

Pred_Ast
Player                  
Aaron Connolly       2.0
Aaron Lennon         1.0
Aaron Mooy           1.0
Adam Idah            1.0
Adam Lallana         1.0
...                  ...
Yoshinori Mutō       1.0
Yves Bissouma        1.0
Érik Lamela          1.0
Étienne Capoue       1.0
İlkay Gündoğan       1.0

[251 rows x 1 columns]

In [144]:
pred_ast_df = forward_players
pred_ast_df

Pred_Ast
Player                  
Aaron Connolly       2.0
Aaron Lennon         1.0
Aaron Mooy           1.0
Adam Idah            1.0
Adam Lallana         1.0
...                  ...
Yoshinori Mutō       1.0
Yves Bissouma        1.0
Érik Lamela          1.0
Étienne Capoue       1.0
İlkay Gündoğan       1.0

[251 rows x 1 columns]

In [145]:
pred_ast_df.to_csv('pred_ast.csv')

In [146]:
y_pred_nn = nn.predict(X_test_scaled)#X_scaler.transform(X))
y_pred_nn
pd.DataFrame({'y_pred_nn': y_pred_nn[:,0], 'y_test': y_test[:,0]})
#y_train[:,0]

y_pred_nn    y_test
0    0.148947  0.169811
1    0.119867  0.142857
2    0.006333  0.000000
3    0.002156  0.000000
4    0.040787  0.105263
..        ...       ...
58   0.005742  0.000000
59   0.018664  0.000000
60   0.092284  0.107692
61   0.115917  0.135135
62   0.136434  0.139535

[63 rows x 2 columns]