In [76]:
import pandas as pd
import numpy as np
import sklearn as skl
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
from tensorflow import keras
from sklearn.metrics import r2_score
import statsmodels.api as sm

In [77]:
player_data = pd.read_csv('/Users/hunter/Desktop/Data_Class/final_project/Data/cleaned_players.csv')

In [78]:
player_data

Player Pos   Min  Gls  Ast   xG  npxG   xA  Sh  SoT  ...  Fld  \
0      Roberto Firmino  FW  86.0    0    1  0.9   0.9  0.4   4    1  ...    1   
1         James Milner  CM   4.0    0    0  0.0   0.0  0.0   0    0  ...    0   
2         Divock Origi  LW  74.0    1    0  0.2   0.2  0.0   1    1  ...    2   
3           Sadio Mané  LW  16.0    0    0  0.0   0.0  0.0   0    0  ...    0   
4        Mohamed Salah  RW  90.0    1    1  0.3   0.3  0.2   2    1  ...    1   
...                ...  ..   ...  ...  ...  ...   ...  ...  ..  ...  ...  ...   
20370     Riyad Mahrez  CM  90.0    1    2  0.1   0.1  0.5   2    2  ...    1   
20371  Christian Fuchs  LB  90.0    0    0  0.0   0.0  0.0   0    0  ...    0   
20372    Harry Maguire  CB  90.0    0    0  0.4   0.4  0.0   4    1  ...    1   
20373       Wes Morgan  CB  90.0    0    0  0.0   0.0  0.0   0    0  ...    0   
20374  Hamza Choudhury  RB  34.0    0    0  0.0   0.0  0.0   1    0  ...    1   

       Crs  TklW  Int  CrdY  CrdR  year  fantasy_points  Position Group League  
0        0     1    0     0     0  2019            10.0         Forward     PL  
1        0     0    0     0     0  2019             1.0        Midfield     PL  
2        4     3    1     0     0  2019            15.0         Forward     PL  
3        0     0    0     0     0  2019             1.0         Forward     PL  
4        7     0    0     0     0  2019            17.5         Forward     PL  
...    ...   ...  ...   ...   ...   ...             ...             ...    ...  
20370    4     1    1     0     0  2018            25.0        Midfield     PL  
20371    1     0    4     0     0  2018             2.0        Defender     PL  
20372    0     2    5     0     0  2018             8.0        Defender     PL  
20373    0     0    3     0     0  2018             2.5        Defender     PL  
20374    0     0    4     1     0  2018            -0.5        Defender     PL  

[20375 rows x 21 columns]

In [79]:
forward_data = player_data[player_data['Position Group'] == 'Forward']
forward_data

Player Pos   Min  Gls  Ast   xG  npxG   xA  Sh  SoT  ...  Fld  \
0      Roberto Firmino  FW  86.0    0    1  0.9   0.9  0.4   4    1  ...    1   
2         Divock Origi  LW  74.0    1    0  0.2   0.2  0.0   1    1  ...    2   
3           Sadio Mané  LW  16.0    0    0  0.0   0.0  0.0   0    0  ...    0   
4        Mohamed Salah  RW  90.0    1    1  0.3   0.3  0.2   2    1  ...    1   
12         Teemu Pukki  FW  83.0    1    0  0.4   0.4  0.1   3    1  ...    1   
...                ...  ..   ...  ...  ...  ...   ...  ...  ..  ...  ...  ...   
20353       Harry Kane  FW  90.0    2    0  0.2   0.2  0.0   3    2  ...    0   
20354      Lucas Moura  LW  74.0    0    1  0.1   0.1  0.0   2    0  ...    2   
20356      Érik Lamela  RW  78.0    2    0  1.3   1.3  0.0   2    2  ...    2   
20361    Son Heung-min  FW   6.0    0    0  0.0   0.0  0.0   0    0  ...    0   
20366      Jamie Vardy  FW  90.0    2    0  0.5   0.5  0.3   6    2  ...    0   

       Crs  TklW  Int  CrdY  CrdR  year  fantasy_points  Position Group League  
0        0     1    0     0     0  2019            10.0         Forward     PL  
2        4     3    1     0     0  2019            15.0         Forward     PL  
3        0     0    0     0     0  2019             1.0         Forward     PL  
4        7     0    0     0     0  2019            17.5         Forward     PL  
12       0     1    1     0     0  2019            15.0         Forward     PL  
...    ...   ...  ...   ...   ...   ...             ...             ...    ...  
20353    0     0    0     0     0  2018            24.5         Forward     PL  
20354    0     0    0     0     0  2018             5.0         Forward     PL  
20356    1     1    2     0     0  2018            26.5         Forward     PL  
20361    0     0    0     0     0  2018             1.0         Forward     PL  
20366    0     0    0     0     0  2018            25.0         Forward     PL  

[5463 rows x 21 columns]

In [80]:
# Groupby player (forward) mean
forward_data_mean = forward_data.groupby(["Player"]).mean()
forward_data_mean.head()

Min       Gls       Ast        xG      npxG        xA  \
Player                                                                        
Aaron Connolly  49.312500  0.125000  0.000000  0.137500  0.137500  0.012500   
Aaron Lennon    73.611111  0.055556  0.055556  0.016667  0.016667  0.050000   
Aaron Mooy      73.846154  0.000000  0.000000  0.053846  0.053846  0.207692   
Adam Idah       65.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
Adam Lallana    23.076923  0.000000  0.076923  0.046154  0.046154  0.023077   

                      Sh       SoT       Fls       Fld       Crs      TklW  \
Player                                                                       
Aaron Connolly  1.437500  0.500000  0.687500  1.625000  0.437500  0.250000   
Aaron Lennon    0.388889  0.166667  0.722222  1.055556  1.777778  0.888889   
Aaron Mooy      1.384615  0.615385  0.384615  0.615385  5.923077  1.461538   
Adam Idah       0.000000  0.000000  0.000000  2.000000  0.000000  3.000000   
Adam Lallana    0.461538  0.000000  0.307692  0.692308  0.538462  0.230769   

                     Int      CrdY  CrdR         year  fantasy_points  
Player                                                                 
Aaron Connolly  0.000000  0.000000   0.0  2019.187500        3.156250  
Aaron Lennon    0.500000  0.055556   0.0  2017.611111        2.138889  
Aaron Mooy      0.384615  0.153846   0.0  2018.846154        2.846154  
Adam Idah       0.000000  0.000000   0.0  2020.000000        2.500000  
Adam Lallana    0.230769  0.153846   0.0  2018.307692        1.230769

In [81]:
forward_players = forward_data_mean.filter(['Player'], axis=1)
forward_players

Empty DataFrame
Columns: []
Index: [Aaron Connolly, Aaron Lennon, Aaron Mooy, Adam Idah, Adam Lallana, Adam Smith, Adama Traoré, Ahmed Elmohamady, Ainsley Maitland-Niles, Albian Ajeti, Alex Iwobi, Alex Oxlade-Chamberlain, Alexandre Lacazette, Alexis Mac Allister, Alireza Jahanbakhsh, Allan Saint-Maximin, Andre Gray, Andreas Pereira, Andriy Yarmolenko, Andros Townsend, Andy Carroll, Angel Gomes, Anthony Gordon, Anthony Martial, Anwar El Ghazi, Armando Broja, Arthur Masuaku, Ashley Barnes, Ayoze Pérez, Ben Chilwell, Ben Osborn, Bernard, Bernardo, Bernardo Silva, Billy Sharp, Borja Bastón, Brandon Williams, Bukayo Saka, Callum Hudson-Odoi, Callum Robinson, Callum Wilson, Calum Chambers, Carlos Sánchez, Cenk Tosun, Che Adams, Cheikhou Kouyaté, Chris Wood, Christian Atsu, Christian Benteke, Christian Eriksen, Christian Pulisic, Ciaran Clark, Connor Wickham, Conor Hourihane, Dan Gosling, Daniel James, Daniel Podence, Danny Ings, Danny Rose, Danny Welbeck, David McGoldrick, DeAndre Yedlin, Declan Rice, Dejan Lovren, Dele Alli, Demarai Gray, Dennis Srbeny, Diego Rico, Diogo Dalot, Diogo Jota, Divock Origi, Domingos Quina, Dominic Calvert-Lewin, Dominic Solanke, Douglas Luiz, Dwight Gayle, Dwight McNeil, Eddie Nketiah, Ederson, Emerson Palmieri, Emi Buendía, Emil Krafth, Eric Dier, Ezequiel Schelotto, Fabinho, Faustino Anjorin, Felipe Anderson, Florin Andone, Gabriel Jesus, Georges-Kévin N'Koudou, Gerard Deulofeu, Giovani Lo Celso, Glenn Murray, Gylfi Sigurðsson, Hamza Choudhury, Harry Kane, Harry Wilson, Harry Winks, Harvey Barnes, Henri Lansbury, ...]

[251 rows x 0 columns]

In [82]:
def backwardElimination(x, sl):
    numVars = len(x[0])
    for i in range(0, numVars):
        regressor_OLS = sm.OLS(y_var, x).fit()
        maxVar = max(regressor_OLS.pvalues).astype(float)
        if maxVar > sl:
            for j in range(0, numVars - i):
                if (regressor_OLS.pvalues[j].astype(float) == maxVar):
                    x = np.delete(x, j, 1)
    regressor_OLS.summary()
    return x

In [83]:
# Create target
y_var = forward_data_mean.Int
y_var.head()

Player
Aaron Connolly    0.000000
Aaron Lennon      0.500000
Aaron Mooy        0.384615
Adam Idah         0.000000
Adam Lallana      0.230769
Name: Int, dtype: float64

In [84]:
player_x = forward_data_mean.drop("Int", axis =1)
player_x.head()

Min       Gls       Ast        xG      npxG        xA  \
Player                                                                        
Aaron Connolly  49.312500  0.125000  0.000000  0.137500  0.137500  0.012500   
Aaron Lennon    73.611111  0.055556  0.055556  0.016667  0.016667  0.050000   
Aaron Mooy      73.846154  0.000000  0.000000  0.053846  0.053846  0.207692   
Adam Idah       65.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
Adam Lallana    23.076923  0.000000  0.076923  0.046154  0.046154  0.023077   

                      Sh       SoT       Fls       Fld       Crs      TklW  \
Player                                                                       
Aaron Connolly  1.437500  0.500000  0.687500  1.625000  0.437500  0.250000   
Aaron Lennon    0.388889  0.166667  0.722222  1.055556  1.777778  0.888889   
Aaron Mooy      1.384615  0.615385  0.384615  0.615385  5.923077  1.461538   
Adam Idah       0.000000  0.000000  0.000000  2.000000  0.000000  3.000000   
Adam Lallana    0.461538  0.000000  0.307692  0.692308  0.538462  0.230769   

                    CrdY  CrdR         year  fantasy_points  
Player                                                       
Aaron Connolly  0.000000   0.0  2019.187500        3.156250  
Aaron Lennon    0.055556   0.0  2017.611111        2.138889  
Aaron Mooy      0.153846   0.0  2018.846154        2.846154  
Adam Idah       0.000000   0.0  2020.000000        2.500000  
Adam Lallana    0.153846   0.0  2018.307692        1.230769

In [85]:
# Create features 
X = player_x
X.head()

Min       Gls       Ast        xG      npxG        xA  \
Player                                                                        
Aaron Connolly  49.312500  0.125000  0.000000  0.137500  0.137500  0.012500   
Aaron Lennon    73.611111  0.055556  0.055556  0.016667  0.016667  0.050000   
Aaron Mooy      73.846154  0.000000  0.000000  0.053846  0.053846  0.207692   
Adam Idah       65.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
Adam Lallana    23.076923  0.000000  0.076923  0.046154  0.046154  0.023077   

                      Sh       SoT       Fls       Fld       Crs      TklW  \
Player                                                                       
Aaron Connolly  1.437500  0.500000  0.687500  1.625000  0.437500  0.250000   
Aaron Lennon    0.388889  0.166667  0.722222  1.055556  1.777778  0.888889   
Aaron Mooy      1.384615  0.615385  0.384615  0.615385  5.923077  1.461538   
Adam Idah       0.000000  0.000000  0.000000  2.000000  0.000000  3.000000   
Adam Lallana    0.461538  0.000000  0.307692  0.692308  0.538462  0.230769   

                    CrdY  CrdR         year  fantasy_points  
Player                                                       
Aaron Connolly  0.000000   0.0  2019.187500        3.156250  
Aaron Lennon    0.055556   0.0  2017.611111        2.138889  
Aaron Mooy      0.153846   0.0  2018.846154        2.846154  
Adam Idah       0.000000   0.0  2020.000000        2.500000  
Adam Lallana    0.153846   0.0  2018.307692        1.230769

In [86]:
X_opt = X.iloc[:,:].values
X_opt

array([[4.93125000e+01, 1.25000000e-01, 0.00000000e+00, ...,
        0.00000000e+00, 2.01918750e+03, 3.15625000e+00],
       [7.36111111e+01, 5.55555556e-02, 5.55555556e-02, ...,
        0.00000000e+00, 2.01761111e+03, 2.13888889e+00],
       [7.38461538e+01, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01884615e+03, 2.84615385e+00],
       ...,
       [4.26969697e+01, 6.06060606e-02, 3.03030303e-02, ...,
        0.00000000e+00, 2.01833333e+03, 2.06060606e+00],
       [9.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 2.00000000e+00],
       [6.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 1.00000000e+00]])

In [87]:
y_var = y_var.reset_index().iloc[:,1:].values

In [88]:
# Test if features are siginiicant 
trimmed_X = backwardElimination(X_opt, 0.05)
trimmed_X

array([[1.25000000e-01, 0.00000000e+00, 1.43750000e+00, ...,
        0.00000000e+00, 2.01918750e+03, 3.15625000e+00],
       [5.55555556e-02, 5.55555556e-02, 3.88888889e-01, ...,
        0.00000000e+00, 2.01761111e+03, 2.13888889e+00],
       [0.00000000e+00, 0.00000000e+00, 1.38461538e+00, ...,
        0.00000000e+00, 2.01884615e+03, 2.84615385e+00],
       ...,
       [6.06060606e-02, 3.03030303e-02, 1.09090909e+00, ...,
        0.00000000e+00, 2.01833333e+03, 2.06060606e+00],
       [0.00000000e+00, 0.00000000e+00, 2.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 2.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 2.01700000e+03, 1.00000000e+00]])

In [89]:
# Split our preprocessed data into our features and target arrays
y = y_var
X = trimmed_X

In [90]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [91]:
# Create scaler instance
scaler = StandardScaler()

In [92]:
# Fit the scaler
X_scaler = scaler.fit(X_train)

In [93]:
# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [94]:
# Define the linear regression model
lin_reg = LinearRegression()

In [95]:
# Train the model
lin_reg.fit(X_train_scaled, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [96]:
lin_reg.score(X_train, y_train)

-2728.754232600888

In [97]:
lin_reg.score(X_test, y_test)

-2520.444825017611

In [98]:
y_pred = lin_reg.predict(X_test)

In [99]:
y_pred_all = lin_reg.predict(X)

In [100]:
r2_score(y_test, y_pred)

-2520.444825017611

In [101]:
# Define hidden layers
number_input_features = len(X_train_scaled[0])
hidden_layer1 = 50
hidden_layer2 = 50

In [102]:
nn = tf.keras.models.Sequential()

In [103]:
# Hidden layer 1
nn.add(tf.keras.layers.Dense(units=hidden_layer1, input_dim=number_input_features, kernel_initializer='normal', activation="relu"))

In [104]:
# Hidden layer 2
nn.add(tf.keras.layers.Dense(units=hidden_layer2, input_dim=number_input_features, kernel_initializer='normal', activation="relu"))

In [105]:
# Output layer
nn.add(tf.keras.layers.Dense(units=1))

In [106]:
# Compile the model
nn.compile(loss="mean_squared_error", optimizer="adam")#, metrics=["accuracy"])

In [107]:
# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 50)                600       
_________________________________________________________________
dense_7 (Dense)              (None, 50)                2550      
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 51        
Total params: 3,201
Trainable params: 3,201
Non-trainable params: 0
_________________________________________________________________


In [108]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Train on 188 samples
Epoch 1/100
188/188 [==============================] - 1s 4ms/sample - loss: 0.2429
Epoch 2/100
188/188 [==============================] - 0s 197us/sample - loss: 0.1924
Epoch 3/100
188/188 [==============================] - 0s 203us/sample - loss: 0.1612
Epoch 4/100
188/188 [==============================] - 0s 159us/sample - loss: 0.1470
Epoch 5/100
188/188 [==============================] - 0s 160us/sample - loss: 0.1367
Epoch 6/100
188/188 [==============================] - 0s 143us/sample - loss: 0.1283
Epoch 7/100
188/188 [==============================] - 0s 127us/sample - loss: 0.1237
Epoch 8/100
188/188 [==============================] - 0s 118us/sample - loss: 0.1199
Epoch 9/100
188/188 [==============================] - 0s 121us/sample - loss: 0.1176
Epoch 10/100
188/188 [==============================] - 0s 222us/sample - loss: 0.1149
Epoch 11/100
188/188 [==============================] - 0s 117us/sample - loss: 0.1120
Epoch 12/100
188/188 [===========

188/188 [==============================] - 0s 112us/sample - loss: 0.0070
Epoch 96/100
188/188 [==============================] - 0s 112us/sample - loss: 0.0071
Epoch 97/100
188/188 [==============================] - 0s 118us/sample - loss: 0.0064
Epoch 98/100
188/188 [==============================] - 0s 105us/sample - loss: 0.0072
Epoch 99/100
188/188 [==============================] - 0s 97us/sample - loss: 0.0068
Epoch 100/100
188/188 [==============================] - 0s 98us/sample - loss: 0.0065


In [109]:
# Evaluate the model using the test data - mean
#model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)
#print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")
model_loss = nn.evaluate(X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}")

63/1 - 0s - loss: 1.8546
Loss: 1.8439108795589871


In [110]:
#y_pred.shape
y_pred_all.shape

(251, 1)

In [111]:
#y_pred
y_pred_all

array([[ 15.48588009],
       [ 11.21904229],
       [ 13.3130275 ],
       [ 12.08899674],
       [  6.65317333],
       [  5.65267712],
       [ 16.98089774],
       [  2.32149566],
       [ 64.03465099],
       [  2.74314919],
       [ 20.54302982],
       [ 16.21422614],
       [ 35.25488017],
       [  7.46322186],
       [ 13.74807642],
       [ 21.16292826],
       [ 20.44116975],
       [  7.07604219],
       [  9.24247216],
       [ 20.76663736],
       [  8.5479998 ],
       [ 14.38175228],
       [ 10.99782843],
       [ 34.84755822],
       [ 23.18726211],
       [  5.65267712],
       [ 19.82326576],
       [ 22.24849455],
       [ 32.1830384 ],
       [  1.24877572],
       [  9.94355687],
       [ 14.43824059],
       [ 19.1997678 ],
       [ 28.22297879],
       [ 11.59500357],
       [  5.65267712],
       [  5.65267712],
       [  7.32994731],
       [ 14.48191039],
       [ 10.61179769],
       [ 28.6377235 ],
       [  1.24877572],
       [  5.65267712],
       [ 20

In [112]:
#np.rint(y_pred)
y_pred_all_clean = np.rint(y_pred_all)
y_pred_all_clean

array([[ 15.],
       [ 11.],
       [ 13.],
       [ 12.],
       [  7.],
       [  6.],
       [ 17.],
       [  2.],
       [ 64.],
       [  3.],
       [ 21.],
       [ 16.],
       [ 35.],
       [  7.],
       [ 14.],
       [ 21.],
       [ 20.],
       [  7.],
       [  9.],
       [ 21.],
       [  9.],
       [ 14.],
       [ 11.],
       [ 35.],
       [ 23.],
       [  6.],
       [ 20.],
       [ 22.],
       [ 32.],
       [  1.],
       [ 10.],
       [ 14.],
       [ 19.],
       [ 28.],
       [ 12.],
       [  6.],
       [  6.],
       [  7.],
       [ 14.],
       [ 11.],
       [ 29.],
       [  1.],
       [  6.],
       [ 20.],
       [  8.],
       [  8.],
       [ 29.],
       [  9.],
       [ 13.],
       [ 38.],
       [ 39.],
       [  6.],
       [ 11.],
       [  6.],
       [  7.],
       [ 22.],
       [ 10.],
       [ 35.],
       [  9.],
       [ 12.],
       [ 13.],
       [  1.],
       [  8.],
       [  6.],
       [ 30.],
       [ 15.],
       [  

In [113]:
y_pred_all_clean[y_pred_all_clean <= 0] = 0
y_pred_all_clean

array([[15.],
       [11.],
       [13.],
       [12.],
       [ 7.],
       [ 6.],
       [17.],
       [ 2.],
       [64.],
       [ 3.],
       [21.],
       [16.],
       [35.],
       [ 7.],
       [14.],
       [21.],
       [20.],
       [ 7.],
       [ 9.],
       [21.],
       [ 9.],
       [14.],
       [11.],
       [35.],
       [23.],
       [ 6.],
       [20.],
       [22.],
       [32.],
       [ 1.],
       [10.],
       [14.],
       [19.],
       [28.],
       [12.],
       [ 6.],
       [ 6.],
       [ 7.],
       [14.],
       [11.],
       [29.],
       [ 1.],
       [ 6.],
       [20.],
       [ 8.],
       [ 8.],
       [29.],
       [ 9.],
       [13.],
       [38.],
       [39.],
       [ 6.],
       [11.],
       [ 6.],
       [ 7.],
       [22.],
       [10.],
       [35.],
       [ 9.],
       [12.],
       [13.],
       [ 1.],
       [ 8.],
       [ 6.],
       [30.],
       [15.],
       [ 1.],
       [ 6.],
       [ 7.],
       [25.],
       [21.],
      

In [114]:
forward_players['Pred_Int'] = y_pred_all_clean
forward_players

Pred_Int
Player                  
Aaron Connolly      15.0
Aaron Lennon        11.0
Aaron Mooy          13.0
Adam Idah           12.0
Adam Lallana         7.0
...                  ...
Yoshinori Mutō       7.0
Yves Bissouma        9.0
Érik Lamela         10.0
Étienne Capoue       9.0
İlkay Gündoğan       6.0

[251 rows x 1 columns]

In [115]:
pred_int_df = forward_players
pred_int_df

Pred_Int
Player                  
Aaron Connolly      15.0
Aaron Lennon        11.0
Aaron Mooy          13.0
Adam Idah           12.0
Adam Lallana         7.0
...                  ...
Yoshinori Mutō       7.0
Yves Bissouma        9.0
Érik Lamela         10.0
Étienne Capoue       9.0
İlkay Gündoğan       6.0

[251 rows x 1 columns]

In [116]:
pred_int_df.to_csv('pred_int.csv')

In [117]:
y_pred_nn = nn.predict(X_test_scaled)#X_scaler.transform(X))
y_pred_nn
pd.DataFrame({'y_pred_nn': y_pred_nn[:,0], 'y_test': y_test[:,0]})

y_pred_nn    y_test
0    7.480401  0.000000
1    0.322571  0.000000
2    0.214792  0.222222
3    0.376599  0.666667
4    0.555126  0.279070
..        ...       ...
58   0.234125  0.000000
59   0.015790  0.103448
60   0.360686  0.150000
61   0.903313  1.000000
62   0.403554  1.000000

[63 rows x 2 columns]